#!/usr/bin/env bash
# Regression tests for the independent panel calibration auditor
# (bin/polylane-taste-calibration-audit.sh).
#
# The auditor never trusts a receipt: it recomputes correctness, Wilson lower
# bound, exact side probe, mirror contradictions, raw-response closure, session
# uniqueness, parser/invocation/config hashes, holdout binding, and
# classification from the raw evidence, then cross-checks the emitted
# taste-calibration/v2 receipt.  Independent arithmetic assertions come first,
# then the adversarial receipt matrix.
set -euo pipefail

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
BIN="$ROOT/bin/polylane-taste-calibration-audit.sh"
LIVE="$ROOT/bin/polylane-taste-calibration-live.sh"
TMPDIR_TEST=$(mktemp -d "${TMPDIR:-/tmp}/polylane-taste-calibration-audit.XXXXXX")
trap 'rm -rf "$TMPDIR_TEST"' EXIT HUP INT TERM
PARSER_SHA=$("$LIVE" parser-sha)

fail() { printf 'FAIL %s\n' "$*" >&2; exit 1; }
hf() { shasum -a 256 "$1" | awk '{print $1}'; }
rep64() { printf '%*s' 64 '' | tr ' ' "$1"; }
tok() { case "$1" in 1) printf FIRST;; 2) printf SECOND;; 0) printf ABSTAIN;; esac; }
mk() { local d="$TMPDIR_TEST/$1"; rm -rf "$d"; mkdir -p "$d"; printf '%s' "$d"; }

SP=$(rep64 1); SAMP=$(rep64 2); SRC=$(rep64 3); ADAPTER=$(rep64 4)
CORPUS=$(rep64 a); TUNING=$(rep64 b)
PROV=example-provider; MODEL=example-model; MV=2026.08

# build_config PANEL-ROOT NAME CORRECT [UNITS] [MODE(file|inline|sidebias)]
# Produces $panel/$name/{input.json,labels.json,resp-*,img-*,receipt.json,sessions.json}.
# The eligibility receipt is generated by the real upstream producer (the live
# validator); the auditor under test must never invoke it.
build_config() {
  local panel=$1 name=$2 correct=$3 units=${4:-24} mode=${5:-file}
  local root="$panel/$name"; mkdir -p "$root"
  local labels="$root/labels.json" input="$root/input.json"
  local labels_arr='[]' units_arr='[]' sessions_arr='[]' i
  for ((i = 0; i < units; i++)); do
    local A="stim-u${i}a" B="stim-u${i}b" gold_pos ppos mpos o0 o1 mo0 mo1
    gold_pos=$(( i % 2 == 0 ? 1 : 2 ))
    if [ "$i" -lt "$correct" ]; then ppos=$gold_pos; mpos=$((3 - gold_pos)); else ppos=$((3 - gold_pos)); mpos=$gold_pos; fi
    if [ "$gold_pos" -eq 1 ]; then o0=$A; o1=$B; else o0=$B; o1=$A; fi
    mo0=$o1; mo1=$o0
    if [ "$mode" = sidebias ]; then ppos=1; mpos=1; fi
    local praw mraw psha msha ppath mpath imgsha imgpath
    praw="Unit $i primary assessment of the pair."$'\n'"FINAL: $(tok "$ppos")"
    mraw="Unit $i mirror assessment of the pair."$'\n'"FINAL: $(tok "$mpos")"
    ppath=""; mpath=""; imgpath=""
    if [ "$mode" = inline ]; then
      psha=$(printf '%s' "$praw" | shasum -a 256 | awk '{print $1}')
      msha=$(printf '%s' "$mraw" | shasum -a 256 | awk '{print $1}')
      imgsha=$(printf 'image-unit-%s' "$i" | shasum -a 256 | awk '{print $1}')
    else
      ppath="resp-$i-primary.txt"; mpath="resp-$i-mirror.txt"; imgpath="img-$i.png"
      printf '%s' "$praw" > "$root/$ppath"; printf '%s' "$mraw" > "$root/$mpath"
      printf 'PNGBYTES-unit-%s' "$i" > "$root/$imgpath"
      psha=$(hf "$root/$ppath"); msha=$(hf "$root/$mpath"); imgsha=$(hf "$root/$imgpath")
    fi
    units_arr=$(jq -n --argjson acc "$units_arr" \
      --arg uid "unit-$i" --arg prompt "prompt-$i" --arg brief "brief-$i" \
      --arg imgsha "$imgsha" --arg imgpath "$imgpath" \
      --arg o0 "$o0" --arg o1 "$o1" --arg mo0 "$mo0" --arg mo1 "$mo1" \
      --arg praw "$praw" --arg psha "$psha" --arg ppath "$ppath" \
      --arg mraw "$mraw" --arg msha "$msha" --arg mpath "$mpath" \
      --arg prov "$PROV" --arg model "$MODEL" --arg mv "$MV" --arg sp "$SP" \
      --arg samp "$SAMP" --arg parser "$PARSER_SHA" --arg adapter "$ADAPTER" --arg mode "$mode" '
      def inv: {provider:$prov, model:$model, model_version:$mv, system_prompt_sha256:$sp, sampling_sha256:$samp, parser_sha256:$parser, adapter_sha256:$adapter};
      def img: if $mode == "inline" then {sha256:$imgsha} else {path:$imgpath, sha256:$imgsha} end;
      def resp($raw; $sha; $path): if $mode == "inline" then {inline:$raw, sha256:$sha} else {path:$path, sha256:$sha} end;
      $acc + [ {
        unit_id:$uid, prompt:$prompt, brief:$brief, image:img,
        primary:{orientation:[$o0,$o1], raw_response:resp($praw;$psha;$ppath), invocation:inv,
                 identity_visible:false, prior_ballots_visible:false, injection_detected:false, judge_discussion:false},
        mirror:{orientation:[$mo0,$mo1], raw_response:resp($mraw;$msha;$mpath), invocation:inv,
                identity_visible:false, prior_ballots_visible:false, injection_detected:false, judge_discussion:false}
      } ]')
    labels_arr=$(jq -n --argjson acc "$labels_arr" --arg uid "unit-$i" --arg imgsha "$imgsha" --arg A "$A" --arg B "$B" '
      $acc + [ {unit_id:$uid, image_sha256:$imgsha, stimulus_ids:[$A,$B], correct_stimulus:$A} ]')
    sessions_arr=$(jq -n --argjson acc "$sessions_arr" --arg uid "unit-$i" --arg name "$name" \
      --arg psha "$psha" --arg msha "$msha" --arg i "$i" '
      $acc + [ {unit_id:$uid, role:"primary", session_id:"sess-\($name)-\($i)-p", response_sha256:$psha},
               {unit_id:$uid, role:"mirror",  session_id:"sess-\($name)-\($i)-m", response_sha256:$msha} ]')
  done
  jq -n --argjson labels "$labels_arr" --arg src "$SRC" '
    {schema_version:"taste-holdout-labels/v1", dataset_id:"human-ui-holdout-v1", partition:"held_out",
     source_snapshot_sha256:$src, tuning_image_shas:[], labels:$labels}' > "$labels"
  local labels_sha; labels_sha=$(hf "$labels")
  jq -n --argjson units "$units_arr" --arg labels_sha "$labels_sha" \
    --arg prov "$PROV" --arg model "$MODEL" --arg mv "$MV" --arg sp "$SP" --arg samp "$SAMP" \
    --arg parser "$PARSER_SHA" --arg adapter "$ADAPTER" --arg src "$SRC" \
    --arg corpus "$CORPUS" --arg tuning "$TUNING" --arg name "$name" '
    {schema_version:2,
     calibration:{dataset_id:"human-ui-holdout-v1", partition:"held_out", label_provenance:"human-labeled",
                  holdout_corpus_receipt_sha256:$corpus, tuning_corpus_receipt_sha256:$tuning,
                  holdout_labels:{path:"labels.json", sha256:$labels_sha}},
     freeze:{provider:$prov, model:$model, model_version:$mv, system_prompt_sha256:$sp, sampling_sha256:$samp,
             response_parser_sha256:$parser, invocation_adapter_sha256:$adapter, source_snapshot_sha256:$src,
             image_orientation_frozen:true},
     judge:{id:"judge-cfg-\($name)", provider:$prov, model:$model, model_version:$mv, system_prompt_sha256:$sp, sampling_sha256:$samp},
     units:$units}' > "$input"
  jq -n --argjson sessions "$sessions_arr" --arg name "$name" '
    {schema_version:"taste-calibration-sessions/v1", judge_id:"judge-cfg-\($name)", sessions:$sessions}' \
    > "$root/sessions.json"
  "$LIVE" "$input" "$root/receipt.json" "$root" >/dev/null 2>&1 || true
}

# regenerate_receipt PANEL NAME — refresh the live receipt after evidence edits
regenerate_receipt() { "$LIVE" "$1/$2/input.json" "$1/$2/receipt.json" "$1/$2" >/dev/null 2>&1 || true; }

# bind_panel PANEL NAME... — write audit-input.json with fresh digests
bind_panel() {
  local panel=$1; shift
  local cfgs='[]' name
  for name in "$@"; do
    cfgs=$(jq -n --argjson acc "$cfgs" --arg name "$name" \
      --arg isha "$(hf "$panel/$name/input.json")" \
      --arg rsha "$(hf "$panel/$name/receipt.json")" \
      --arg ssha "$(hf "$panel/$name/sessions.json")" '
      $acc + [ {config_id:("cfg-" + $name),
                calibration_input:{path:"\($name)/input.json", sha256:$isha},
                eligibility_receipt:{path:"\($name)/receipt.json", sha256:$rsha},
                sessions:{path:"\($name)/sessions.json", sha256:$ssha}} ]')
  done
  jq -n --argjson cfgs "$cfgs" \
    '{schema_version:"taste-calibration-audit/v1", run:"test-audit-run", configurations:$cfgs}' \
    > "$panel/audit-input.json"
}

run_audit() { "$BIN" "$1/audit-input.json" "$1/out.json"; }
cfg0() { jq -r ".configurations[0].$1" "$2/out.json"; }

edit_json() { # file jq-program
  jq "$2" "$1" > "$1.n" && mv "$1.n" "$1"
}

assert_cfg_code() { # panel code name
  if run_audit "$1"; then fail "$3: expected non-zero panel rejection"; fi
  test "$(jq -r '.panel.eligible' "$1/out.json")" = false || fail "$3: panel must be ineligible"
  test "$(jq -r '.panel.claim' "$1/out.json")" = null || fail "$3: no claim on ineligible panel"
  test "$(cfg0 eligible "$1")" = false || fail "$3: config must be ineligible"
  jq -e --arg c "$2" '.configurations[0].reason_codes | index($c) != null' "$1/out.json" >/dev/null \
    || fail "$3: expected code $2, got $(jq -c '.configurations[0].reason_codes' "$1/out.json")"
}

# ------------------------------------------------- independent arithmetic first
test_arithmetic_wilson_17_of_24() {
  local d; d=$(mk arith17); build_config "$d" a 17; bind_panel "$d" a
  run_audit "$d" && fail 'arith17: single config cannot satisfy the panel floor'
  test "$(cfg0 eligible "$d")" = true || fail 'arith17: config must be eligible'
  test "$(cfg0 units "$d")" = 24 || fail 'arith17: units 24'
  test "$(cfg0 correct "$d")" = 17 || fail 'arith17: correct 17'
  awk -v v="$(cfg0 accuracy "$d")" 'BEGIN{exit !(v>0.708332 && v<0.708334)}' || fail 'arith17: accuracy 17/24'
  awk -v v="$(cfg0 wilson_lcb_95 "$d")" 'BEGIN{exit !(v>0.508322 && v<0.508324)}' \
    || fail "arith17: wilson lcb 17/24 must be 0.508323, got $(cfg0 wilson_lcb_95 "$d")"
  test "$(cfg0 side_probe_n "$d")" = 24 || fail 'arith17: side probe n'
  awk -v v="$(cfg0 side_probe_exact_binomial_p "$d")" 'BEGIN{exit !(v>0.83 && v<0.85)}' \
    || fail 'arith17: exact side p for 13/24'
  test "$(cfg0 mirror_probe_n "$d")" = 24 || fail 'arith17: mirror probe n'
  test "$(cfg0 mirror_contradictions "$d")" = 0 || fail 'arith17: no contradictions'
  test "$(cfg0 classification "$d")" = production || fail 'arith17: file-backed is production'
}

test_arithmetic_side_tie_p_is_one() {
  local d; d=$(mk tie); build_config "$d" a 24; bind_panel "$d" a
  run_audit "$d" || true
  test "$(cfg0 eligible "$d")" = true || fail 'tie: config eligible'
  # p=1 collapses Wilson to exactly 1/(1+z^2/n) = 0.8620236 for n=24
  awk -v v="$(cfg0 wilson_lcb_95 "$d")" 'BEGIN{exit !(v>0.862023 && v<0.862025)}' \
    || fail "tie: wilson lcb 24/24 must be 0.862024, got $(cfg0 wilson_lcb_95 "$d")"
  test "$(cfg0 side_probe_exact_binomial_p "$d")" = 1.000000 \
    || fail "tie: balanced 12/24 sides is an exact tie, p must clamp to 1.000000, got $(cfg0 side_probe_exact_binomial_p "$d")"
}

test_parser_sha_matches_pinned_contract() {
  test "$("$BIN" parser-sha)" = "$PARSER_SHA" || fail 'auditor must pin the identical response parser'
}

# ------------------------------------------------- panel aggregation
test_panel_eligible_with_five_production_configs() {
  local d; d=$(mk panel5)
  local n; for n in a b c d e; do build_config "$d" "$n" 17; done
  bind_panel "$d" a b c d e
  run_audit "$d" || fail 'panel5: expected panel-eligible exit 0'
  test "$(jq -r '.panel.eligible' "$d/out.json")" = true || fail 'panel5: panel eligible'
  test "$(jq -r '.panel.claim' "$d/out.json")" = HUMAN_CALIBRATED_MACHINE || fail 'panel5: panel claim'
  test "$(jq -r '.panel.eligible_production_configurations' "$d/out.json")" = 5 || fail 'panel5: five production configs'
  test "$(jq -r '.human_certified' "$d/out.json")" = false || fail 'panel5: never human_certified'
  test "$(jq -r '.machine_not_human' "$d/out.json")" = true || fail 'panel5: machine_not_human'
  test "$(jq -r '.configurations[0] | has("machine_panel_claim")' "$d/out.json")" = false \
    || fail 'panel5: the claim exists only at panel level'
  test "$(jq -r '.configurations[0] | has("human_certified")' "$d/out.json")" = false \
    || fail 'panel5: human_certified is a panel-level constant only'
  test "$(jq -r '.response_parser_sha256' "$d/out.json")" = "$PARSER_SHA" || fail 'panel5: parser sha bound'
  test "$(jq -r '.input_sha256' "$d/out.json")" = "$(hf "$d/audit-input.json")" || fail 'panel5: input sha bound'
  test "$(jq -r '.auditor.fingerprint' "$d/out.json")" = "$(hf "$BIN")" || fail 'panel5: auditor fingerprint'
}

test_panel_floor_with_four_configs() {
  local d; d=$(mk panel4)
  local n; for n in a b c d; do build_config "$d" "$n" 17; done
  bind_panel "$d" a b c d
  if run_audit "$d"; then fail 'panel4: four configs must fail the panel floor'; fi
  test "$(jq -r '.panel.eligible' "$d/out.json")" = false || fail 'panel4: panel ineligible'
  test "$(jq -r '.panel.claim' "$d/out.json")" = null || fail 'panel4: no claim below the floor'
  jq -e '.panel.reason_codes | index("PANEL_FLOOR") != null' "$d/out.json" >/dev/null || fail 'panel4: PANEL_FLOOR'
}

test_fixture_configs_never_reach_production_panel() {
  local d; d=$(mk fixture5)
  local n; for n in a b c d e; do build_config "$d" "$n" 17 24 inline; done
  bind_panel "$d" a b c d e
  if run_audit "$d"; then fail 'fixture5: inline fixtures can never form a production panel'; fi
  test "$(cfg0 eligible "$d")" = true || fail 'fixture5: fixture config may pass its gates'
  test "$(cfg0 classification "$d")" = fixture_only || fail 'fixture5: classification fixture_only'
  test "$(jq -r '.panel.eligible_production_configurations' "$d/out.json")" = 0 || fail 'fixture5: zero production'
  jq -e '.panel.reason_codes | index("PANEL_FLOOR") != null' "$d/out.json" >/dev/null || fail 'fixture5: PANEL_FLOOR'
  test "$(jq -r '.panel.claim' "$d/out.json")" = null || fail 'fixture5: no panel claim from fixtures'
}

# ------------------------------------------------- boundary gates
test_boundary_accuracy_floor() {
  local d; d=$(mk acc); build_config "$d" a 16; bind_panel "$d" a
  assert_cfg_code "$d" ACCURACY_FLOOR acc
}
test_boundary_wilson_floor() {
  local d; d=$(mk wil); build_config "$d" a 24 40; bind_panel "$d" a
  assert_cfg_code "$d" WILSON_FLOOR wilson
}
test_boundary_side_bias() {
  local d; d=$(mk side); build_config "$d" a 17 24 sidebias; bind_panel "$d" a
  assert_cfg_code "$d" SIDE_BIAS side
}
test_boundary_mirror_contradictions() {
  # 19 correct, then flip two mirror responses: 17 correct, exactly 2 contradictions.
  local d; d=$(mk mirror); build_config "$d" a 19
  local i
  for i in 0 1; do
    local mraw msha
    mraw="Unit $i mirror flipped."$'\n'"FINAL: $(tok $(( i % 2 == 0 ? 1 : 2 )))"
    printf '%s' "$mraw" > "$d/a/resp-$i-mirror.txt"; msha=$(hf "$d/a/resp-$i-mirror.txt")
    edit_json "$d/a/input.json" ".units[$i].mirror.raw_response.sha256 = \"$msha\""
    edit_json "$d/a/sessions.json" "(.sessions[] | select(.unit_id == \"unit-$i\" and .role == \"mirror\") | .response_sha256) |= \"$msha\""
  done
  regenerate_receipt "$d" a; bind_panel "$d" a
  assert_cfg_code "$d" MIRROR_INSTABILITY mirror
  test "$(cfg0 mirror_contradictions "$d")" = 2 || fail 'mirror: exactly 2 contradictions recomputed'
  test "$(cfg0 correct "$d")" = 17 || fail 'mirror: correctness unaffected by side choice'
}

# ------------------------------------------------- sessions
test_duplicate_session_ids_rejected() {
  local d; d=$(mk sdup); build_config "$d" a 17
  edit_json "$d/a/sessions.json" '.sessions[1].session_id = .sessions[0].session_id'
  bind_panel "$d" a
  assert_cfg_code "$d" SESSION_REUSE sdup
}
test_session_missing_or_unbound_rejected() {
  local d; d=$(mk sunb); build_config "$d" a 17
  edit_json "$d/a/sessions.json" '.sessions |= .[1:]'
  bind_panel "$d" a
  assert_cfg_code "$d" SESSION_UNBOUND sunb
}
test_cross_config_session_reuse_rejected_at_panel() {
  local d; d=$(mk sxcfg)
  local n; for n in a b c d e; do build_config "$d" "$n" 17; done
  edit_json "$d/b/sessions.json" '.sessions[0].session_id = "sess-a-0-p"'
  bind_panel "$d" a b c d e
  if run_audit "$d"; then fail 'sxcfg: cross-config session reuse must fail the panel'; fi
  jq -e '.panel.reason_codes | index("SESSION_REUSE") != null' "$d/out.json" >/dev/null \
    || fail 'sxcfg: panel-level SESSION_REUSE'
}

# ------------------------------------------------- adversarial receipt matrix
test_stale_config_receipt() {
  local d; d=$(mk stale); build_config "$d" a 17
  edit_json "$d/a/receipt.json" '.judge_configuration.system_prompt_sha256 = "'"$(rep64 9)"'"'
  bind_panel "$d" a
  assert_cfg_code "$d" STALE_CONFIG stale
}
test_changed_holdout_after_receipt() {
  local d; d=$(mk holdout); build_config "$d" a 17; bind_panel "$d" a
  edit_json "$d/a/labels.json" '.labels[0].correct_stimulus = .labels[0].stimulus_ids[1]'
  assert_cfg_code "$d" HOLDOUT_BINDING holdout
}
test_receipt_numbers_tampered() {
  local d; d=$(mk rnum); build_config "$d" a 17
  edit_json "$d/a/receipt.json" '.correct_units = 24 | .correct = 24 | .accuracy = 1'
  bind_panel "$d" a
  assert_cfg_code "$d" RECEIPT_MISMATCH rnum
}
test_human_claim_escalation_rejected() {
  local d; d=$(mk hclaim); build_config "$d" a 17
  edit_json "$d/a/receipt.json" '.human_certified = true'
  bind_panel "$d" a
  assert_cfg_code "$d" HUMAN_CLAIM hclaim
  jq -e '.panel.reason_codes | index("HUMAN_CLAIM") != null' "$d/out.json" >/dev/null \
    || fail 'hclaim: human-claim escalation poisons the panel'
  test "$(jq -r '.human_certified' "$d/out.json")" = false || fail 'hclaim: audit stays human_certified:false'
}
test_synthetic_response_binding_rejected() {
  local d; d=$(mk synth); build_config "$d" a 17
  edit_json "$d/a/input.json" '.units[0].primary.raw_response.path = "does-not-exist.txt"'
  bind_panel "$d" a
  assert_cfg_code "$d" SYNTHETIC_RECEIPT synth
}
test_config_binding_digest_mismatch() {
  local d; d=$(mk cbind); build_config "$d" a 17; bind_panel "$d" a
  edit_json "$d/a/input.json" '.calibration.dataset_id = "tampered-after-binding"'
  assert_cfg_code "$d" CONFIG_BINDING cbind
}
test_parser_change_rejected() {
  local d; d=$(mk parser); build_config "$d" a 17
  edit_json "$d/a/input.json" '.freeze.response_parser_sha256 = "'"$(rep64 8)"'"'
  bind_panel "$d" a
  assert_cfg_code "$d" PARSER_CHANGED parser
}
test_audit_input_must_be_clean_json() {
  local d; d=$(mk badinput); mkdir -p "$d"
  printf '{"schema_version":"taste-calibration-audit/v1","run":"x","run":"y","configurations":[]}' \
    > "$d/audit-input.json"
  if run_audit "$d"; then fail 'badinput: duplicate-key audit input must be rejected'; fi
  jq -e '.panel.reason_codes | index("AUDIT_INPUT_INVALID") != null' "$d/out.json" >/dev/null \
    || fail 'badinput: AUDIT_INPUT_INVALID'
}

test_arithmetic_wilson_17_of_24
test_arithmetic_side_tie_p_is_one
test_parser_sha_matches_pinned_contract
test_panel_eligible_with_five_production_configs
test_panel_floor_with_four_configs
test_fixture_configs_never_reach_production_panel
test_boundary_accuracy_floor
test_boundary_wilson_floor
test_boundary_side_bias
test_boundary_mirror_contradictions
test_duplicate_session_ids_rejected
test_session_missing_or_unbound_rejected
test_cross_config_session_reuse_rejected_at_panel
test_stale_config_receipt
test_changed_holdout_after_receipt
test_receipt_numbers_tampered
test_human_claim_escalation_rejected
test_synthetic_response_binding_rejected
test_config_binding_digest_mismatch
test_parser_change_rejected
test_audit_input_must_be_clean_json

printf 'PASS test-taste-calibration-audit assertions=21\n'
