#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2034 # sourced runner consumes fixture globals
# Promotion is a transaction: runner-owned durable state may be committed
# narrowly before the verified merge, while user work is never staged or merged.

. "$(cd "$(dirname "$0")" && pwd)/helpers.sh"
. "$RUNNER"

promotion_fixture() {
  make_tmpdir
  REPO_ROOT="$TEST_TMPDIR/repo"
  PROJECT_ROOT="$REPO_ROOT"
  BASE=main
  INT_BRANCH=lane/integrator
  git init -q "$REPO_ROOT"
  git -C "$REPO_ROOT" config user.email polylane-test@example.invalid
  git -C "$REPO_ROOT" config user.name 'Polylane Test'
  git -C "$REPO_ROOT" checkout -q -b "$BASE"
  mkdir -p "$REPO_ROOT/docs/polylane/workers"
  printf 'base\n' > "$REPO_ROOT/README.md"
  printf '{"cycle":13}\n' > "$REPO_ROOT/docs/polylane/max-state.json"
  printf '{"seq":1}\n' > "$REPO_ROOT/docs/polylane/workers/history.jsonl"
  git -C "$REPO_ROOT" add README.md docs/polylane/max-state.json docs/polylane/workers/history.jsonl
  git -C "$REPO_ROOT" commit -qm base
  git -C "$REPO_ROOT" checkout -q -b "$INT_BRANCH"
  printf 'verified product\n' > "$REPO_ROOT/product.txt"
  git -C "$REPO_ROOT" add product.txt
  git -C "$REPO_ROOT" commit -qm verified
  git -C "$REPO_ROOT" checkout -q "$BASE"
}

# Cycle 13: pre-promotion telemetry/history writes dirtied an otherwise valid
# base, so git refused the verified merge. Those exact runner-owned paths are
# safe to stage explicitly and must not require staging the whole worktree.
promotion_fixture
printf '{"cycle":14}\n' > "$REPO_ROOT/docs/polylane/max-state.json"
printf '{"seq":2}\n' >> "$REPO_ROOT/docs/polylane/workers/history.jsonl"
promote_to_main; runner_owned_rc=$?
assert_eq "runner-owned-dirt-promotes" "0" "$runner_owned_rc"
assert_ok "runner-owned-dirt-merged-verified-tip" git -C "$REPO_ROOT" merge-base --is-ancestor "$INT_BRANCH" HEAD
assert_eq "runner-owned-dirt-clean-after-transaction" "" "$(git -C "$REPO_ROOT" status --porcelain)"
assert_contains "runner-owned-dirt-committed-narrowly" "polylane: record runner state before promotion" "$(git -C "$REPO_ROOT" log --format=%s -n 2)"

# Skill-use evidence is generated by record_skill_use_evidence before the
# integrator starts. Its canonical ledger and only the current run's named
# lane receipts are runner-owned durable state, so both must survive the
# pre-promotion transaction and the verified integration merge.
promotion_fixture
RUN_ID=c14-owned-skill-use
LANE_NAMES=(lane-a)
mkdir -p "$REPO_ROOT/docs/polylane/skill-use/$RUN_ID"
printf '%s\n' '{"lane":"lane-a","skill":"fixture-test","outcome":"unused"}' > "$REPO_ROOT/docs/polylane/skill-outcomes.jsonl"
printf '%s\n' '{"lane":"lane-a","unused":["fixture-test"]}' > "$REPO_ROOT/docs/polylane/skill-use/$RUN_ID/lane-a.json"
printf '%s\n' '{"cycle":14,"cost":42,"verdict":"GO"}' > "$REPO_ROOT/docs/polylane/spend-ledger.jsonl"
promote_to_main; skill_evidence_rc=$?
assert_eq "runner-skill-ledger-promotes" "0" "$skill_evidence_rc"
assert_ok "runner-skill-ledger-reaches-promoted-base" git -C "$REPO_ROOT" merge-base --is-ancestor "$INT_BRANCH" HEAD
assert_contains "runner-skill-ledger-is-durable" '"skill":"fixture-test"' "$(git -C "$REPO_ROOT" show HEAD:docs/polylane/skill-outcomes.jsonl)"
assert_contains "runner-skill-receipt-is-durable" '"lane":"lane-a"' "$(git -C "$REPO_ROOT" show "HEAD:docs/polylane/skill-use/$RUN_ID/lane-a.json")"
assert_contains "runner-spend-ledger-is-durable" '"cost":42' "$(git -C "$REPO_ROOT" show HEAD:docs/polylane/spend-ledger.jsonl)"
assert_eq "runner-skill-evidence-clean-after-transaction" "" "$(git -C "$REPO_ROOT" status --porcelain)"

# The runner and verified candidate may update the same durable state file.
# A single conflict is auto-resolved only when frozen structure + learning log
# match and the candidate monotonically advances stale status.
promotion_fixture
STATE_FILE=docs/polylane/max-state.json
git -C "$REPO_ROOT" checkout -q "$INT_BRANCH"
cat > "$REPO_ROOT/$STATE_FILE" <<'JSON'
{"ultimate":"ship","criteria":[{"id":"c1","text":"works","weight":1,"status":"done","score":0}],"milestones":[{"id":"m1","text":"build","subgoals":[{"id":"s1","text":"ship","weight":1,"status":"done","cycle":14,"evidence":"verified"}]}],"accept":[{"sid":"s1","cmd":"test -f product.txt","tier":"terminal","status":"pass","deps":[],"fp":"","regressed_cycle":null}],"log":[{"cycle":14,"kind":"decision","text":"same learning"}]}
JSON
git -C "$REPO_ROOT" add "$STATE_FILE"
git -C "$REPO_ROOT" commit -qm 'verified terminal state'
git -C "$REPO_ROOT" checkout -q "$BASE"
cat > "$REPO_ROOT/$STATE_FILE" <<'JSON'
{"ultimate":"ship","criteria":[{"id":"c1","text":"works","weight":1,"status":"open","score":0}],"milestones":[{"id":"m1","text":"build","subgoals":[{"id":"s1","text":"ship","weight":1,"status":"open","cycle":null,"evidence":""}]}],"accept":[{"sid":"s1","cmd":"test -f product.txt","tier":"terminal","status":"fail","deps":[],"fp":"","regressed_cycle":null}],"log":[{"cycle":14,"kind":"decision","text":"same learning"}]}
JSON
promote_to_main; monotonic_state_rc=$?
assert_eq "monotonic-state-conflict-promotes" "0" "$monotonic_state_rc"
assert_eq "monotonic-state-takes-verified-criterion" "done" "$(jq -r '.criteria[] | select(.id == "c1") | .status' "$REPO_ROOT/$STATE_FILE")"
assert_eq "monotonic-state-takes-verified-acceptance" "pass" "$(jq -r '.accept[] | select(.sid == "s1") | .status' "$REPO_ROOT/$STATE_FILE")"
assert_eq "monotonic-state-preserves-learning" "same learning" "$(jq -r '.log[0].text' "$REPO_ROOT/$STATE_FILE")"
assert_eq "monotonic-state-index-clean" "" "$(git -C "$REPO_ROOT" ls-files --unmerged)"

# A candidate with a different durable learning log is not safe to select.
promotion_fixture
STATE_FILE=docs/polylane/max-state.json
git -C "$REPO_ROOT" checkout -q "$INT_BRANCH"
cat > "$REPO_ROOT/$STATE_FILE" <<'JSON'
{"ultimate":"ship","criteria":[{"id":"c1","text":"works","weight":1,"status":"done","score":0}],"milestones":[{"id":"m1","text":"build","subgoals":[{"id":"s1","text":"ship","weight":1,"status":"done","cycle":14,"evidence":"verified"}]}],"accept":[{"sid":"s1","cmd":"test -f product.txt","tier":"terminal","status":"pass","deps":[],"fp":"","regressed_cycle":null}],"log":[{"cycle":14,"kind":"decision","text":"candidate learning"}]}
JSON
git -C "$REPO_ROOT" add "$STATE_FILE"
git -C "$REPO_ROOT" commit -qm 'candidate divergent learning'
git -C "$REPO_ROOT" checkout -q "$BASE"
cat > "$REPO_ROOT/$STATE_FILE" <<'JSON'
{"ultimate":"ship","criteria":[{"id":"c1","text":"works","weight":1,"status":"open","score":0}],"milestones":[{"id":"m1","text":"build","subgoals":[{"id":"s1","text":"ship","weight":1,"status":"open","cycle":null,"evidence":""}]}],"accept":[{"sid":"s1","cmd":"test -f product.txt","tier":"terminal","status":"fail","deps":[],"fp":"","regressed_cycle":null}],"log":[{"cycle":14,"kind":"decision","text":"base learning"}]}
JSON
promote_to_main; divergent_state_rc=$?
assert_eq "divergent-state-conflict-blocks" "1" "$divergent_state_rc"
assert_fail "divergent-state-does-not-merge-candidate" git -C "$REPO_ROOT" merge-base --is-ancestor "$INT_BRANCH" HEAD
assert_eq "divergent-state-preserves-base-learning" "base learning" "$(jq -r '.log[0].text' "$REPO_ROOT/$STATE_FILE")"
assert_eq "divergent-state-index-clean" "" "$(git -C "$REPO_ROOT" ls-files --unmerged)"

# A user edit is not runner state. It blocks promotion before the base moves,
# remains present and unstaged, and leaves the verified integration branch for
# a later deliberate resolution.
promotion_fixture
before=$(git -C "$REPO_ROOT" rev-parse HEAD)
printf 'user edit\n' >> "$REPO_ROOT/README.md"
promote_to_main; user_dirt_rc=$?
assert_eq "user-dirt-blocks-promotion" "1" "$user_dirt_rc"
assert_eq "user-dirt-base-unchanged" "$before" "$(git -C "$REPO_ROOT" rev-parse HEAD)"
assert_contains "user-dirt-survives-untouched" "user edit" "$(cat "$REPO_ROOT/README.md")"
assert_eq "user-dirt-not-implicitly-staged" " M README.md" "$(git -C "$REPO_ROOT" status --porcelain)"

# A non-fast-forward conflict is also a failed transaction: the base ref and
# index return to their pre-attempt state, and cleanup remains ineligible.
promotion_fixture
git -C "$REPO_ROOT" checkout -q "$INT_BRANCH"
printf 'integrator edit\n' > "$REPO_ROOT/README.md"
git -C "$REPO_ROOT" commit -am 'integrator conflict' -q
git -C "$REPO_ROOT" checkout -q "$BASE"
printf 'base edit\n' > "$REPO_ROOT/README.md"
git -C "$REPO_ROOT" commit -am 'base conflict' -q
conflict_before=$(git -C "$REPO_ROOT" rev-parse HEAD)
promote_to_main; conflict_rc=$?
assert_eq "merge-conflict-fails-transaction" "1" "$conflict_rc"
assert_eq "merge-conflict-base-ref-unchanged" "$conflict_before" "$(git -C "$REPO_ROOT" rev-parse HEAD)"
assert_eq "merge-conflict-index-clean" "" "$(git -C "$REPO_ROOT" ls-files --unmerged)"
assert_eq "merge-conflict-state-failed" "failed" "${PROMOTION_STATE:-}"

finish
